import { DeliveryServiceListGroupType } from "./types/DeliveryServiceListGroupType";

export const deliveryServicesList: DeliveryServiceListGroupType[] = [
	{
		title: "Total Departments",
		links: [
			{ title: "Fresh Produce", url: "https://www.instacart.com/categories/316-food/317-fresh-produce" },
			{ title: "Dairy Products", url: "https://www.instacart.com/categories/316-food/1326-dairy" },
			{ title: "Meat", url: "https://www.instacart.com/categories/316-food/1807-meat" },
			{ title: "Meat Alternatives", url: "https://www.instacart.com/categories/316-food/831-meat-alternatives" },
			{ title: "Seafood", url: "https://www.instacart.com/categories/316-food/1974-seafood" },
			{ title: "Pantry Food", url: "https://www.instacart.com/categories/316-food/844-pantry" },
			{ title: "Baked Goods", url: "https://www.instacart.com/categories/316-food/1300-baked-goods" },
			{ title: "View all departments", url: "https://www.instacart.com/categories" },
			{ title: "Gift Delivery Near Me", url: "https://www.instacart.com/gift-delivery" },
			{ title: "Flower Delivery Near Me", url: "https://www.instacart.com/gift-delivery" },
			{ title: "Asian Groceries", url: "https://www.instacart.com/asian-grocery-delivery" },
			{ title: "Business Office Food", url: "https://www.instacart.com/business/office-food" },
			{ title: "Coffee Shop Supplies", url: "https://www.instacart.com/business/coffee-shop-supplies" },
		],
	},
	{
		title: "More Departments",
		links: [
			{ title: "Alcohol", url: "https://www.instacart.com/categories/2-alcohol" },
			{ title: "Alcohol by location", url: "https://www.instacart.com/alcohol-delivery" },
			{ title: "Frozen Food", url: "https://www.instacart.com/categories/316-food/627-frozen-food" },
			{ title: "Beverages", url: "https://www.instacart.com/categories/243-beverages" },
			{ title: "Organic Grocery", url: "https://www.instacart.com/store/hub/grocery" },
			{ title: "Household Essentials", url: "https://www.instacart.com/categories/1361-household-essentials" },
			{ title: "Office Supplies", url: "https://www.instacart.com/categories/1764-office-supplies" },
			{ title: "Beauty Products", url: "https://www.instacart.com/categories/1484-beauty" },
			{ title: "Late Night Delivery", url: "https://www.instacart.com/late-night-delivery" },
			{ title: "Grocery Pickup Near me", url: "https://www.instacart.com/gift-delivery" },
			{ title: "Latin Groceries", url: "https://www.instacart.com/asian-grocery-delivery" },
			{ title: "Business Office snacks", url: "https://www.instacart.com/business/office-snacks" },
		],
	},
	{
		title: "Instacart Programs",
		links: [
			{ title: "Instacart+", url: "https://www.instacart.com/instacart-plus" },
			{ title: "Instacart Business", url: "https://www.instacart.com/business/" },
			{ title: "EBT SNAP", url: "https://www.instacart.com/ebt-snap" },
			{ title: "Fresh Funds", url: "https://www.instacart.com/freshfunds" },
			{ title: "Promos & Coupons", url: "https://www.instacart.com/promos-and-coupons" },
			{ title: "Gift Cards", url: "https://www.instacart.com/p/gift-cards" },
			{ title: "Grocery Budget Calculator", url: "https://www.instacart.com/resources/grocery-budget-calculator" },
			{ title: "Instacart Ads", url: "https://www.instacart.com/categories/316-food/317-fresh-produce" },
			{ title: "Instacart Connect", url: "https://docs.instacart.com/connect/?_gl=1*15sbulg*_ga*NjQyOTY1NjE4LjE3MDQ5MDE4ODA.*_ga_VL5WVTXMWP*MTcwNTYzMTA3Ni4yNy4xLjE3MDU2MzMxMjkuOS4wLjA." },
			{ title: "Cookie Delivery Near me", url: "https://www.instacart.com/cookie-delivery" },
			{ title: "Business Office Supplies", url: "https://www.instacart.com/business/office-supplies" },
			{ title: "Home Depot Delivery", url: "https://www.instacart.com/store/the-home-depot/storefront" },
		],
	},
	{
		title: "Get to know us",
		links: [
			{ title: "Press", url: "https://www.instacart.com/company/newsroom/?_gl=1*du1tjf*_ga*NjQyOTY1NjE4LjE3MDQ5MDE4ODA.*_ga_VL5WVTXMWP*MTcwNTYzMTA3Ni4yNy4xLjE3MDU2MzM0NzYuNjAuMC4w" },
			{ title: "Careers", url: "https://instacart.careers/?_gl=1%2Ag0n9nt%2A_ga%2ANjQyOTY1NjE4LjE3MDQ5MDE4ODA.%2A_ga_VL5WVTXMWP%2AMTcwNTYzNjY4Ni4yOC4wLjE3MDU2MzY2ODYuNjAuMC4w" },
			{ title: "Blog", url: "https://www.instacart.com/company/blog?_gl=1*g0n9nt*_ga*NjQyOTY1NjE4LjE3MDQ5MDE4ODA.*_ga_VL5WVTXMWP*MTcwNTYzNjY4Ni4yOC4wLjE3MDU2MzY2ODYuNjAuMC4w" },
			{ title: "Ideas & Guides", url: "https://www.instacart.com/company/ideas/?_gl=1*126722h*_ga*NjQyOTY1NjE4LjE3MDQ5MDE4ODA.*_ga_VL5WVTXMWP*MTcwNTYzNjY4Ni4yOC4xLjE3MDU2MzY3MTIuMzQuMC4w" },
			{ title: "Help", url: "https://www.instacart.com/help" },
			{ title: "Shop By Location", url: "https://www.instacart.com/grocery-delivery" },
			{ title: "Beauty Supplies Near Me", url: "https://www.instacart.com/beauty-supply-delivery" },
			{ title: "Pet Supplies Near Me", url: "https://www.instacart.com/pet-supplies-delivery" },
			{ title: "Convenience Store Near Me", url: "https://www.instacart.com/convenience-store-delivery" },
			{ title: "Cake Delivery Near Me", url: "https://www.instacart.com/cake-delivery" },
			{ title: "Caper Cart", url: "https://www.instacart.com/connected-stores/caper-cart" },
		],
	},
];
